[#SCMS-94] - add *.map files to gitignore, update locked packages, update README with commands
markmiscavage/scarlet pull request #37
Opened 2020-08-27 20:45 UTC by lukaszjagodzinski

2020-08-27 21:18 UTC, markmiscavage approved these changes

2020-08-27 22:07 UTC, deserat requested changes

2020-08-27 22:07 UTC, deserat commented on README.md
> +Which install all necessary packages for front-end part.
installs

2020-08-27 22:07 UTC, deserat commented on README.md
> +For make changes and generate css/js files after save run:
To make changes

2020-08-27 22:07 UTC, deserat commented on README.md
> +Before push to PR run:
Before you push to PR

2020-08-27 22:07 UTC, deserat commented on README.md
> +For test and linter run:
To test and lint

2020-08-27 22:10 UTC, lukaszjagodzinski commented on README.md
> +Which install all necessary packages for front-end part.
done

2020-08-27 22:10 UTC, lukaszjagodzinski commented on README.md
> +For make changes and generate css/js files after save run:
done

2020-08-27 22:10 UTC, lukaszjagodzinski commented on README.md
> +Before push to PR run:
done

2020-08-27 22:10 UTC, lukaszjagodzinski commented on README.md
> +For test and linter run:
done

2020-08-28 15:31 UTC, markmiscavage approved these changes

2020-08-28 15:32 UTC, merged